### ISSUE TITLE
curl: (25) Failed FTP upload: 553  

### ISSUE THREAD

**Issue by edouard-lopez** [panubo/docker-vsftpd#1]
I'm running you container and try to send files using `curl` but it fails.

### Running the container

```
export FTP_USER="test"
export FTP_PASSWORD="test"

docker run \
    --name mock_ftp_server \
    --publish 21:21 \
    --publish 4559-4564:4559-4564 \
    --env FTP_USER="$FTP_USER" \
    --env FTP_PASSWORD="$FTP_PASSWORD" \
    --detach \
  panubo/vsftpd
```

### Sending file

```
$ curl --upload-file /tmp/mock.data-2017-03-28.tar.gz ftp://localhost --user $FTP_USER:$FTP_PASSWORD
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                               Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (25) Failed FTP upload: 553
```

### Question

What's the matter here? Do I need to add something?

**Comment by edouard-lopez** [comment]
I fixed it by changing the owner of the root directory (`/srv/) to the FTP user `ftp`:

    docker run …
    docker exec mock_ftp_server chown ftp:ftp -R /srv/
    curl …

Could you confirm that's not a security risk?

**Comment by trnubo** [comment]
Hi Edouard

You will need to make your own assessment we are unable to tell you if this is a security risk in your environment.

If you want to be able to write to a file or directory the `ftp` user must have write permissions which you have done via `chown ftp:ftp -R /srv/` in the container.

**Comment by edouard-lopez** [comment]
@trnubo Thanks for your concern, this issue arise in the context of running my project's tests. So no security risk as this is not happening on production and never will.
