### ISSUE TITLE
multiple users

### ISSUE THREAD

**Issue by egorsmorgunov** [panubo/docker-vsftpd#10]
Can not understand how variables look to multiple users?
For one
      -e FTP_USER=user1
      -e FTP_PASSWORD=password1
      -v '/backups:/srv/'

FTP_USER_* ?
FTP_USER_user1=  ? what?

**Comment by macropin** [comment]
For `FTP_USER_* ` vars the format is `FTP_USER_x=username:hash`. 

Example:

```
FTP_USER_1=foo:$6$kbj5ipqKEpabjlxq$W8ixlqvWtkWld1E3igvRgZtvUCo/dQBidryFUs.gKi6vskbx45wCUg0BwX0V511yyFE75eeyMHPZ9cSM..sDm1
FTP_USER_2=bar:$6$/doixasfnbqRyuMj$dWyQ6jW7js498GA0t85nxT4iPPCzopdf32lNxQDdovjxEGN.VrHlmqy0nN51klEGoSXfElsRXn04IxYeixkkk1
```

**Comment by egorsmorgunov** [comment]
Thanks, hash generation:
python3 -c 'import crypt; print(crypt.crypt("password", crypt.mksalt(crypt.METHOD_SHA512)))'

**Comment by peadarDoyle** [comment]
For anyone on Windows, I found the easiest way to generate the hash is to just run your docker-vsftpd container and then ssh into it (i.e. `docker exec -it containername /bin/bash`) and then run `mkpasswd -m sha-512`.

Not entirely related, but I also got tripped up by not escaping the $ symbol in the hash in my docker-compose.yml file. So to escape you replace $ with $$.
