### ISSUE TITLE
Cant write on subdirectories  

### ISSUE THREAD

**Issue by dudu** [panubo/docker-vsftpd#12]
In need of a pre-created structure i.e:
```
/srv/downloads
/srv/uploads
```

I tried to generate a image:
```
FROM panubo/vsftpd

VOLUME /srv/downloads
VOLUME /srv/uploads
```
But on `entry.sh` the ownership is only aplied to `srv`, blocking access of ftp user on subdirectories.

**Comment by trnubo** [comment]
Changing `FTP_CHOWN_ROOT` to recursive is likely not what you want. This will result in users being allowed to upload to `/srv` which is outside of your volumes.

```
-rw-r--r--    1 ftp      ftp            94 Aug 13 23:11 Dockerfile
drwxr-xr-x    2 ftp      ftp          4096 Aug 13 23:10 downloads
drwxr-xr-x    2 ftp      ftp          4096 Aug 13 23:10 uploads
```

I think this will require a new function to chown a defined list of directories, something like `FTP_CHOWN_PATHS=/srv/downloads:/srv/uploads`. I'll look to implement something like this.
