### ISSUE TITLE
time is missing

### ISSUE THREAD

**Issue by egorsmorgunov** [panubo/docker-vsftpd#16]
Ftp connect: time is missing

![image](https://user-images.githubusercontent.com/16851393/58554695-5483d100-8220-11e9-85db-0dcb5e79e29f.png)
sftp connect: Time is present

![image](https://user-images.githubusercontent.com/16851393/58554748-74b39000-8220-11e9-9a95-a8970814dd6a.png)

**Comment by trnubo** [comment]
This is likely a client issue. It is common for clients to exclude the time when the modified date is not in the current year (as shown in your example).

Either way this is not likely an issue with the docker image.
