### ISSUE TITLE
FTP_USER_* not working because of unquoted Here String

### ISSUE THREAD

**Issue by RichardBronosky** [panubo/docker-vsftpd#2]
In line 18 https://github.com/panubo/docker-vsftpd/blob/master/entry.sh#L18 `${!user}` is unquoted.

    IFS=: read name pass <<< ${!user}

I was unable to add multiple users until I changed it to 

    IFS=: read name pass <<< "${!user}"

Consider this simple demo

	$ export FTP_USER_UNO='one:111'

	$ export FTP_USER_DOS='two:222'

	$ while read user; do
	>     IFS=':' read name pass <<< ${!user}
	>     echo "Adding user $name"
	>     echo "($pass)"
	> done < <(env | grep "FTP_USER_" | sed 's/^\(FTP_USER_[a-zA-Z0-9]*\)=.*/\1/')
	Adding user two 222
	()
	Adding user one 111
	()

	$ while read user; do
	>     IFS=':' read name pass <<< "${!user}"
	>     echo "Adding user $name"
	>     echo "($pass)"
	> done < <(env | grep "FTP_USER_" | sed 's/^\(FTP_USER_[a-zA-Z0-9]*\)=.*/\1/')
	Adding user two
	(222)
	Adding user one
	(111)

**Comment by trnubo** [comment]
I was unable to replicate your issue.

```
root@0c36bc025f50:/# export FTP_USER_UNO='one:111'
root@0c36bc025f50:/# export FTP_USER_DOS='two:222'
root@0c36bc025f50:/# while read user; do
>     IFS=':' read name pass <<< ${!user}
>     echo "Adding user $name"
>     echo "($pass)"
> done < <(env | grep "FTP_USER_" | sed 's/^\(FTP_USER_[a-zA-Z0-9]*\)=.*/\1/')
Adding user two
(222)
Adding user one
(111)
root@0c36bc025f50:/# 
```

I don't know why this didn't work for you. Never the less the entry.sh could do with a clean up it is not very consistent with indenting, quotes and braces around variables.
