### ISSUE TITLE
Default serving directory permissions prevent writing.

### ISSUE THREAD

**Issue by gamesh411** [panubo/docker-vsftpd#4]
The default /src directory has the owner root with group root, and permisson 755, thus preventing vsftpd to write to the directory.
The issue could be resolved by the following solution: the directory should be owned by the user of the vsftpd, named 'ftp'.

What do you think, is there any problem with this solution?

**Comment by trnubo** [comment]
Hi, changing the owner of /srv to ftp would be an insecure default. We don't want a default or miss configured setup to become open to attack or abuse. Additionally as /srv is a volume setting the owner in the Dockerfile won't always work. `docker run -v /ftp_root:/srv panubo/vsftpd` will assume the directory owner of /ftp_root on the host and won't be influenced by the Dockerfile.

For this to be considered it could be an option for entry.sh, something like `ALLOW_WRITABLE_ROOT=true` and the entry.sh will update the directory owner.

**Comment by gamesh411** [comment]
I haven't considered what would happen in case a volume were to be used instead. Your point is definitely valid, and I must agree that changing the owner of the root serving directory should only be considered if the said directory does not have a volume bound to it AND the the user of the container explicitly declares that the root itself should be writable.

I will update my PR to reflect these insights.
